trigger:
  branches:
    include:
      - main

  paths:
    include:
      - deploy/*
      - src/*

variables:
  - name: solution
    value: "src/VBar.Setups.sln"
  - name: buildConfiguration
    value: "Release"

pool:
  vmImage: "windows-latest"
    
steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: "$(solution)"

  - task: VSBuild@1
    inputs:
      solution: "$(solution)"
      configuration: "$(buildConfiguration)"

  # - task: VSTest@2
  #   inputs:
  #     testAssemblyVer2: |
  #       !**\*test.XXX.dll
  #       !**\*test.YYY.dll
  #       **\*test*.dll
  #       !**\obj\**
  #       vsTestVersion: 16.0
  #       runInParallel: true
  #       codeCoverageEnabled: false
  #       diagnosticsEnabled: true

  - task: CopyFiles@2
    displayName: "Copy Files to: $(build.artifactstagingdirectory)"
    inputs:
      SourceFolder: "$(system.defaultworkingdirectory)"
      Contents: '**\bin\$(BuildConfiguration)\**'
      TargetFolder: "$(build.artifactstagingdirectory)"
