trigger:
  - deploy/*
  - src/*

pool:
  vmImage: "windows-latest"

variables:
  - name: solution
    value: "src/VBar.Setups.sln"
  - name: buildConfiguration
    value: "Release"

steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: "$(solution)"

  - task: VSBuild@1
    inputs:
      solution: "$(solution)"
      configuration: "$(buildConfiguration)"

  - task: CopyFiles@2
    displayName: "Copy Files to: $(build.artifactstagingdirectory)"
    inputs:
      SourceFolder: "$(system.defaultworkingdirectory)"
      Contents: '**\bin\$(BuildConfiguration)\**'
      TargetFolder: "$(build.artifactstagingdirectory)"
