trigger:
  branches:
    include:
      - main

  paths:
    include:
      - deploy/build.yaml
      - src/VBar.Setups/*

variables:
  - name: solution
    value: 'src/VBar.Setups.sln'
  - name: buildConfiguration
    value: 'Release'
  - name: projectPath
    value: 'src/VBar.Setups'

pool:
  vmImage: 'windows-latest'
    
steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    displayName: 'Restore'
    inputs:
      restoreSolution: '$(solution)'

  - task: VSBuild@1
    displayName: 'Build'
    inputs:
      solution: '$(solution)'
      configuration: '$(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: 'test'
      arguments: '--no-build --configuration $(buildConfiguration)'
      publishTestResults: true
      projects: '**/*.Tests.csproj'

  - task: NuGetCommand@2
    displayName: 'Pack'
    inputs:
      command: pack
      packagesToPack: 'src/VBar.Setups/VBar.Setups.csproj'
      packDestination: '$(Build.ArtifactStagingDirectory)'      

  # - task: DotNetCoreCLI@2
  #   displayName: 'Clean'
  #   inputs:
  #     command: custom
  #     projects: '$(projectPath)'
  #     custom: clean
        
  - task: CopyFiles@2
    displayName: 'Copy'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: '**\VBar.Setups.*.nupkg'
      TargetFolder: '$(build.artifactstagingdirectory)'
      