trigger:
  - deploy/*.*
  - src/*.*

pool:
  vmImage: "windows-latest"

variables:
  - name: solution
    value: "src/VBar.Setups.sln"
  - name: buildConfiguration
    value: "Release"

steps:
  - task: VSBuild@1
    inputs:
      solution: "$(solution)"
      configuration: "$(buildConfiguration)"
